class AppStrings {
  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'appName': 'ReVive',
      'tagline': 'National E-Waste Circular Exchange',
      'searchPlaceholder': 'Search materials, recyclers, prices...',
      'navHome': 'Home',
      'navScan': 'Scan Scrap',
      'navPrices': 'Price Board',
      'navLots': 'My Lots',
      'navRecyclers': 'Recyclers',
      'navEarnings': 'Earnings',
      'navSafety': 'Safety',
      'navProfile': 'ID Card',
      'scanHeroTitle': 'Live AI Vision Camera Scanner',
      'scanHeroSub': 'Point camera at e-waste for instant scrap classification & MSP cash valuation',
      'btnScanNow': '📷 Open Live Camera Scanner',
      'btnSellNow': '⚡ Sell Now / Book Pickup',
      'rateTickerTitle': 'Today’s Verified E-Waste MSP Rates',
      'recentLotsTitle': 'My Recent Scrap Lots',
      'roleCollector': 'Kabadiwala Collector',
      'roleRecycler': 'CPCB Authorized Recycler',
      'roleAdmin': 'Platform Administrator',
      'statusOnline': 'Online',
      'statusOffline': 'Offline Queue',
      'audioAssistant': 'Listen Audio',
    },
    'hi': {
      'appName': 'री-वाइव',
      'tagline': 'राष्ट्रीय ई-कचरा चक्रीय विनिमय',
      'searchPlaceholder': 'सामग्री, रीसाइक्लर, लाइव भाव खोजें...',
      'navHome': 'मुख्य',
      'navScan': 'स्कैन करें',
      'navPrices': 'लाइव भाव',
      'navLots': 'मेरे लॉट',
      'navRecyclers': 'रीसाइक्लर',
      'navEarnings': 'कमाई',
      'navSafety': 'सुरक्षा',
      'navProfile': 'पहचान पत्र',
      'scanHeroTitle': 'लाइव एआई कैमरा विज़न स्कैनर',
      'scanHeroSub': 'ई-कचरे पर कैमरा लगाएं और तुरंत सही एमएसपी मूल्य व नकद भाव पाएं',
      'btnScanNow': '📷 कैमरा स्कैनर शुरू करें',
      'btnSellNow': '⚡ तुरंत बेचें / पिकअप बुक करें',
      'rateTickerTitle': 'आज के प्रमाणित न्यूनतम समर्थन मूल्य (MSP)',
      'recentLotsTitle': 'हाल ही में दर्ज कबाड़ लॉट',
      'roleCollector': 'कबाड़ीवाला साथी',
      'roleRecycler': 'प्रमाणित रीसाइक्लर',
      'roleAdmin': 'प्रशासक',
      'statusOnline': 'ऑनलाइन',
      'statusOffline': 'ऑफ़लाइन कतार',
      'audioAssistant': 'ऑडियो सुनें',
    },
    'mr': {
      'appName': 'री-व्हाइव्ह',
      'tagline': 'राष्ट्रीय ई-कचरा परिपत्र विनिमय',
      'searchPlaceholder': 'सामग्री, रिसायकलर, लाइव्ह भाव शोधा...',
      'navHome': 'मुख्य',
      'navScan': 'स्कॅन करा',
      'navPrices': 'बाजार भाव',
      'navLots': 'माझे लॉट',
      'navRecyclers': 'रिसायकलर्स',
      'navEarnings': 'कमाई',
      'navSafety': 'सुरक्षा',
      'navProfile': 'ओळखपत्र',
      'scanHeroTitle': 'थेट एआय कॅमेरा व्हिजन स्कॅनर',
      'scanHeroSub': 'ई-कचऱ्यावर कॅमेरा धरा आणि अचूक दर व रोख किंमत त्वरित मिळवा',
      'btnScanNow': '📷 थेट कॅमेरा सुरू करा',
      'btnSellNow': '⚡ लगेच विका / पिकअप बुक करा',
      'rateTickerTitle': 'आजचे प्रमाणित ई-कचरा हमीभाव',
      'recentLotsTitle': 'माझे अलीकडील लॉट्स',
      'roleCollector': 'कबाडीवाला मित्र',
      'roleRecycler': 'प्रमाणित रिसायकलर',
      'roleAdmin': 'प्रशासक',
      'statusOnline': 'ऑनलाइन',
      'statusOffline': 'ऑफलाइन रांग',
      'audioAssistant': 'ऑडिओ ऐका',
    },
  };

  static String get(String key, String lang) {
    return localizedValues[lang]?[key] ?? localizedValues['en']?[key] ?? key;
  }
}
